version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.0
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  weaviate-rag:
    image: semitechnologies/weaviate:1.25.0
    ports:
      - "8081:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'rag-node'
    volumes:
      - weaviate_rag_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  weaviate-analytics:
    image: semitechnologies/weaviate:1.25.0
    ports:
      - "8082:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'analytics-node'
    volumes:
      - weaviate_analytics_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  php:
    image: php:8.3-cli
    working_dir: /app
    volumes:
      - .:/app
      - composer_cache:/tmp/composer
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer
      WEAVIATE_HOST: weaviate
      WEAVIATE_PORT: 8080
      WEAVIATE_SCHEME: http
      WEAVIATE_RAG_HOST: weaviate-rag
      WEAVIATE_RAG_PORT: 8080
      WEAVIATE_ANALYTICS_HOST: weaviate-analytics
      WEAVIATE_ANALYTICS_PORT: 8080
    depends_on:
      weaviate:
        condition: service_healthy
      weaviate-rag:
        condition: service_healthy
      weaviate-analytics:
        condition: service_healthy
    command: tail -f /dev/null

volumes:
  weaviate_data:
  weaviate_rag_data:
  weaviate_analytics_data:
  composer_cache:
